In [3]:
import numpy as np

# Define a function to create a magic-like matrix
def create_magic_like(n):
    magic_square = np.zeros((n, n), dtype=int)
    row, col = 0, n // 2
    num = 1

    while num <= n * n:
        magic_square[row, col] = num
        num += 1
        new_row, new_col = (row - 1) % n, (col + 1) % n
        if magic_square[new_row, new_col]:
            row += 1
        else:
            row, col = new_row, new_col

    return magic_square

# Generate a 5x5 "magic-like" matrix
A = create_magic_like(5)
# Define column vector b
b = np.array([10, 26, 42, 59, 38])
# Print matrix A and vector b
print("Matrix A:")
print(A)
print("\nVector b:", b)
# Solve the system Ax = b using numpy's solve function
x = np.linalg.solve(A, b)

# Print the solution vector x
print("\nSolution vector x:")
print(x)

# Calculate the residual r = A*x - b
r = np.dot(A, x) - b
# Print the residual vector r
print("\nResidual vector r:")
print(r)


Matrix A:
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Vector b: [10 26 42 59 38]

Solution vector x:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.10542736e-15]


In [5]:
import scipy.linalg

# Perform LU decomposition of A
P, L, U = scipy.linalg.lu(A)  # Note: Use scipy.linalg.lu for LU decomposition

# Solve the system Ax = b using LU decomposition
x1 = np.linalg.solve(A, b)

# Calculate the error between solutions
err1 = np.dot(A, x1) - b

# Print matrices P, L, U and vectors x1, err1
print("Matrix P (Permutation matrix):")
print(P)
print("\nMatrix L (Lower triangular matrix):")
print(L)
print("\nMatrix U (Upper triangular matrix):")
print(U)
print("\nSolution vector x1:")
print(x1)
print("\nError vector err1:")
print(err1)


Matrix P (Permutation matrix):
[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Matrix L (Lower triangular matrix):
[[1.         0.         0.         0.         0.        ]
 [0.73913043 1.         0.         0.         0.        ]
 [0.47826087 0.76873662 1.         0.         0.        ]
 [0.17391304 0.25267666 0.5163652  1.         0.        ]
 [0.43478261 0.48394004 0.72308355 0.92307692 1.        ]]

Matrix U (Upper triangular matrix):
[[ 23.           5.           7.          14.          16.        ]
 [  0.          20.30434783  -4.17391304  -2.34782609   3.17391304]
 [  0.           0.          24.8608137   -2.89079229  -1.09207709]
 [  0.           0.           0.          19.65116279  18.97932817]
 [  0.           0.           0.           0.         -22.22222222]]

Solution vector x1:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Error vector err1:
[ 0.00000000e+00  3.55271368e-15  0.00000000e+00  0.00000000e+00
 -7.

In [6]:
# Solve the system Ax = b using numpy's least squares function
y = np.linalg.lstsq(A, b, rcond=None)[0]
# Print the solution vector y
print("\nSolution vector y:")
print(y)


Solution vector y:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]


In [7]:
# Solve the system Ax = b using matrix inverse
A_inv = np.linalg.inv(A)
x2 = np.dot(A_inv, b)

# Calculate the residual r2 and error err2
r2 = np.dot(A, x2) - b
err2 = x - x2

# Print solution vector x2, residual r2 and error err2
print("\nSolution vector x2 using inverse:")
print(x2)
print("\nResidual vector r2:")
print(r2)
print("\nError vector err2:")
print(err2)


Solution vector x2 using inverse:
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r2:
[-3.55271368e-15 -3.55271368e-15 -7.10542736e-15  0.00000000e+00
 -7.10542736e-15]

Error vector err2:
[-7.63278329e-17  4.16333634e-17  0.00000000e+00  4.44089210e-16
  5.55111512e-17]


In [8]:
def rref(A):
    A = A.astype(float)
    m, n = A.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        if A[r, lead] == 0:
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    A[r, i] = A[i, r]
                    break
        if A[r, lead] != 0:
            A[r] = A[r] / A[r, lead]
            for i in range(m):
                if i != r:
                    A[i] = A[i] - A[i, lead] * A[r]
        lead += 1
    return A

# Compute reduced row echelon form of [A | b]
print(A)
print(b)
C = np.hstack((A, b.reshape(-1, 1)))
print("[A|B] matrix:", C)
R = rref(C)

# Extract solution vector x3 from the RREF matrix
x3 = R[:, -1]

# Calculate residuals
r3 = np.dot(A, x3) - b
err3 = x - x3

print("\nSolution vector x3 (from RREF):")
print(x3)
print("\nResidual vector r3 (from RREF):")
print(r3)
print("\nError vector err3 (difference between x and x3):")
print(err3)


[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]
[10 26 42 59 38]
[A|B] matrix: [[17 24  1  8 15 10]
 [23  5  7 14 16 26]
 [ 4  6 13 20 22 42]
 [10 12 19 21  3 59]
 [11 18 25  2  9 38]]

Solution vector x3 (from RREF):
[-0.00833333  0.0724359   1.47179487  1.48782051 -0.33141026]

Residual vector r3 (from RREF):
[1.77635684e-15 7.10542736e-15 0.00000000e+00 2.13162821e-14
 0.00000000e+00]

Error vector err3 (difference between x and x3):
[-2.67147415e-16  9.71445147e-17  0.00000000e+00 -4.44089210e-16
  2.22044605e-16]


In [13]:
import time
Num=500;
A=np.random.rand(Num,Num)+Num*np.eye(Num)
b=np.random.rand(Num,1)

# Method 1: Solve using solve operator
start_time = time.time()
x1 = np.linalg.solve(A, b)
end_time = time.time()
time_backslash = end_time - start_time

# Method 2: Solve using matrix inverse
start_time = time.time()
x2 = np.linalg.inv(A) @ b
end_time = time.time()
time_inv = end_time - start_time

# Method 3: Solve using reduced row echelon form (rref)
start_time = time.time()
C = np.hstack((A, b))
R = rref(C)
x3 = R[:, -1]
end_time = time.time()
time_rref = end_time - start_time

# Print the solution vectors and computational times
print("\nSolution vector x1 (using backslash operator):")
print(x1)

print("\nSolution vector x2 (using matrix inverse):")
print(x2)

print("\nSolution vector x3 (using reduced row echelon form):")
print(x3)

print("\nComputational times:")
print(f"Backslash operator: {time_backslash} seconds")
print(f"Matrix inverse: {time_inv} seconds")
print(f"Reduced row echelon form (rref): {time_rref} seconds")



Solution vector x1 (using backslash operator):
[[-2.51560389e-04]
 [ 1.42110945e-03]
 [-1.37435877e-04]
 [-1.02707383e-04]
 [-2.90450813e-04]
 [ 6.08846303e-04]
 [ 5.48101668e-04]
 [-2.53210671e-04]
 [ 5.76954745e-04]
 [ 2.87530350e-04]
 [ 1.33464572e-03]
 [ 1.59545654e-03]
 [-3.01860461e-04]
 [ 1.47137008e-03]
 [ 1.45959072e-03]
 [ 1.22391714e-04]
 [ 1.00428681e-03]
 [ 1.63604764e-04]
 [ 2.93815802e-04]
 [ 1.13529096e-03]
 [-2.63617496e-04]
 [ 6.34042762e-04]
 [ 3.95198997e-05]
 [ 6.60509216e-04]
 [ 1.45938861e-03]
 [-1.92442141e-04]
 [ 7.00607939e-04]
 [ 1.40372623e-03]
 [ 1.38271676e-03]
 [ 8.57361916e-04]
 [-2.44943889e-04]
 [ 3.15839988e-04]
 [ 9.87875641e-05]
 [ 9.96254833e-04]
 [ 6.63324300e-04]
 [ 1.04612959e-03]
 [ 8.33443296e-04]
 [ 1.36314018e-04]
 [ 1.50940106e-03]
 [ 1.52159505e-03]
 [ 1.41858293e-03]
 [ 8.29715376e-04]
 [ 2.56029066e-04]
 [ 1.28496305e-03]
 [ 1.53492462e-04]
 [-1.91866467e-04]
 [-2.74783519e-04]
 [ 1.24276689e-03]
 [-1.66663711e-04]
 [-3.39999422e-05]
 [

In [14]:
import numpy as np

# Define matrix A and vector b for the underdetermined system
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

b = np.array([1, 3, 5, 7]).reshape(-1, 1)  # Remove the reshape, as it's unnecessary

# Solve the system Ax = b using the backslash operator
x = np.linalg.lstsq(A, b, rcond=None)[0]  # rcond: This parameter is used to determine the cutoff 
# for small singular values in the computation of the least squares solution.

# [0] takes the first value of answer among all possible answers. Result is a tuple.

# Calculate the residual r1 = Ax - b
r1 = np.dot(A, x) - b

# Print the solution vector x
print("\nSolution vector x:")
print(x)

# Print the residual vector r1
print("\nResidual vector r1:")
print(r1)

# Obtain another particular solution using the pseudoinverse pinv(A)
A_pinv = np.linalg.pinv(A)
y = np.dot(A_pinv, b)

# Calculate the residual r2 = Ax - b for solution y
r2 = np.dot(A, y) - b

# Print the solution vector y from pseudoinverse
print("\nSolution vector y (from pseudoinverse):")
print(y)

# Print the residual vector r2
print("\nResidual vector r2:")
print(r2)



Solution vector x:
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r1:
[[8.8817842e-16]
 [8.8817842e-16]
 [8.8817842e-16]
 [0.0000000e+00]]

Solution vector y (from pseudoinverse):
[[0.38888889]
 [0.22222222]
 [0.05555556]]

Residual vector r2:
[[ 1.55431223e-15]
 [-4.44089210e-16]
 [-2.66453526e-15]
 [-4.44089210e-15]]
