In [1]:
import numpy as np

# 1. Determine the length of a matrix or vector.
A = np.array([[0, 2, 0], [0, 5, 1], [7, 0, 9]])
B = np.array([1, 1, 1])
print("Length of A:", len(A))
print("Length of B:", len(B))

# 2. Add B as the fourth row of A to create C.
C = np.vstack((A, B))
print("Matrix C:")
print(C)

# 3. Create D from rows 2, 3, 4 and columns 3, 4 of C.
D = C[1:4, 1:3]
print("Matrix D:")
print(D)

# 4. Transpose D to create E.
E = D.T
print("Matrix E:")
print(E)

# 5. Check the size of E.
print("Size of E:", E.shape)

# 6. Create equally spaced vectors.
v = np.linspace(0, 10, 5)
print("Equally spaced vector:", v)

# 7. Find the max and min in each column of A.
print("Max in each column of A:", np.max(A, axis=0))
print("Min in each column of A:", np.min(A, axis=0))

# 8. Find the max and min in each row of A.
print("Max in each row of A:", np.max(A, axis=1))
print("Min in each row of A:", np.min(A, axis=1))

# 9. Calculate mean and sum in each column and row of A.
print("Mean of each column in A:", np.mean(A, axis=0))
print("Sum of each row in A:", np.sum(A, axis=1))

# 10. Create random matrices F and G.
F = np.random.rand(3, 3)
G = np.random.rand(3, 3)
print("Matrix F:")
print(F)
print("Matrix G:")
print(G)

# 11. Perform scalar multiplication, addition, subtraction, and element-wise multiplication on F and G.
print("F * 2:")
print(F * 2)
print("F + G:")
print(F + G)
print("F - G:")
print(F - G)
print("F * G (element-wise):")
print(F * G)

# 12. Check the size of F and A, then perform matrix multiplication if dimensions are compatible.
if F.shape[1] == A.shape[0]:
    print("Matrix multiplication F @ A:")
    print(F @ A)
else:
    print("Matrix multiplication not possible due to incompatible dimensions.")

# 13. Generate the following special matrices:
identity_matrix = np.eye(3)
zero_matrix_5x3 = np.zeros((5, 3))
zero_matrix_4x2 = np.zeros((4, 2))
diagonal_matrix = np.diag([1, 2, 7])
random_matrix = np.random.rand(6, 6)
diagonal_elements = np.diag(random_matrix)
sparse_diag = np.diag([1, 2, 3, 4])
dense_matrix = sparse_diag.astype(float)

print("Identity matrix:")
print(identity_matrix)
print("Zero matrix (5x3):")
print(zero_matrix_5x3)
print("Zero matrix (4x2):")
print(zero_matrix_4x2)
print("Diagonal matrix S:")
print(diagonal_matrix)
print("Extracted diagonal elements:")
print(diagonal_elements)
print("Sparse diagonal matrix converted to dense:")
print(dense_matrix)


Length of A: 3
Length of B: 3
Matrix C:
[[0 2 0]
 [0 5 1]
 [7 0 9]
 [1 1 1]]
Matrix D:
[[5 1]
 [0 9]
 [1 1]]
Matrix E:
[[5 0 1]
 [1 9 1]]
Size of E: (2, 3)
Equally spaced vector: [ 0.   2.5  5.   7.5 10. ]
Max in each column of A: [7 5 9]
Min in each column of A: [0 0 0]
Max in each row of A: [2 5 9]
Min in each row of A: [0 0 0]
Mean of each column in A: [2.33333333 2.33333333 3.33333333]
Sum of each row in A: [ 2  6 16]
Matrix F:
[[1.89522662e-01 3.57979260e-01 9.83952079e-01]
 [2.96477340e-01 8.96377986e-01 1.58041245e-01]
 [1.79721702e-04 8.65644396e-01 4.09125496e-01]]
Matrix G:
[[0.15549337 0.2253346  0.80152977]
 [0.73313964 0.23401476 0.02709907]
 [0.51015923 0.94043152 0.76073256]]
F * 2:
[[3.79045324e-01 7.15958521e-01 1.96790416e+00]
 [5.92954679e-01 1.79275597e+00 3.16082489e-01]
 [3.59443404e-04 1.73128879e+00 8.18250992e-01]]
F + G:
[[0.34501603 0.58331386 1.78548185]
 [1.02961698 1.13039275 0.18514032]
 [0.51033896 1.80607592 1.16985806]]
F - G:
[[ 0.03402929  0.13264466